version: '3.7'
services:
    code-editor-app:
        container_name: code-editor-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
